codecov:
  require_ci_to_pass: true

fixes:
  - "/home/runner/work/rexhr/rexhr/::"

coverage:
  status:
    project:
      default:
        informational: true
    patch:
      default:
        informational: true
